import SwiftUI

// swiftlint:disable identifier_name
public enum SafePreviewDevice: String {
    var previewDevice: PreviewDevice { PreviewDevice(rawValue: self.rawValue) }
    case mac = "Mac"
    case iphone7 = "iPhone 7"
    case iphone7plus = "iPhone 7 Plus"
    case iphone8 = "iPhone 8"
    case iphone8plus = "iPhone 8 Plus"
    case iphoneSE = "iPhone SE (2nd generation)"
    case iphoneX = "iPhone X"
    case iphoneXS = "iPhone Xs"
    case iphoneXSMax = "iPhone Xs Max"
    case iphone11Pro = "iPhone 11 Pro"
    case iphone11ProMax = "iPhone 11 Pro Max"
    case iphoneXR = "iPhone Xʀ"
    case iphone11 = "iPhone 11"
    case ipadPro_9_7_inch = "iPad Pro (9.7-inch)"
    case ipadPro_10_5 = "iPad Pro (10.5-inch)"
    case ipadPro_11_inch = "iPad Pro (11-inch)"
    case ipadPro_12_9_inch = "iPad Pro (12.9-inch)"
    case ipadPro_12_9_inch_2ndGen = "iPad Pro (12.9-inch) (2nd generation)"
    case ipadPro_12_9_inch_3rdGen = "iPad Pro (12.9-inch) (3rd generation)"
    case ipad_5thGen = "iPad (5th generation)"
    case ipad_6thGen = "iPad (6th generation)"
    case ipadMini4 = "iPad mini 4"
    case ipadMini_5thGen = "iPad mini (5th generation)"
    case ipadAir2 = "iPad Air 2"
    case ipadAir_3rdGen = "iPad Air (3rd generation)"
    case appletv = "Apple TV"
    case appletv_4k = "Apple TV 4K"
    case appletv_4k_at1080p = "Apple TV 4K (at 1080p)"
    case appleWatch2_38mm = "Apple Watch Series 2 - 38mm"
    case appleWatch3_38mm = "Apple Watch Series 3 - 38mm"
    case appleWatch4_40mm = "Apple Watch Series 4 - 40mm"
    case appleWatch2_42mm = "Apple Watch Series 2 - 42mm"
    case appleWatch3_42mm = "Apple Watch Series 3 - 42mm"
    case appleWatch4_44mm = "Apple Watch Series 4 - 44mm"
}
