name: Build and test all  platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

# Cancel duplicate runs
# https://stackoverflow.com/a/72408109/6942800
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} 
    strategy:
      fail-fast: false
      matrix:
        xcode: ['14.1', '14.0.1', '13.2.1']
        macos: ['macos-12']
        scheme: ['Casimir']
        command: ['test']
        platform: ['macOS', 'iOS', 'tvOS', 'watchOS']  
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Fastlane
      uses: maierj/fastlane-action@v3.0.0
      with:
          lane: 
    
    # - name: Switch xcode to ${{ matrix.xcode }}
    #   uses: maxim-lobanov/setup-xcode@v1.2.3
    #   with:
    #     xcode-version: ${{ matrix.xcode }}
    # - name: Double-check macOS version (${{ matrix.macos }})
    #   run: sw_vers
    
    # - name: Check xcodebuild version
    #   run: xcodebuild -version
    # - name: Check xcode embedded SDKs
    #   run: xcodebuild -showsdks
    # - name: Show buildable schemes
    #   run: xcodebuild -list
    # - name: Show eligible build destinations for ${{ matrix.scheme }}
    #   run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
    # - uses: mxcl/xcodebuild@v1.9.2
    #   with:
    #     platform: ${{ matrix.platform }}
    #     scheme: ${{ matrix.scheme }}
    #     action: ${{ matrix.command }} 
    #     code-coverage: true
    #     verbosity: xcpretty
    #     upload-logs: always



    # todo: fastlane - env