name: Build and test all  platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build_and_test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} 
    strategy:
      fail-fast: false
      matrix:
        xcode: ['13.2.1', '13.0', '12.5.1', '12.4', '12.0.1']
        macos: ['macos-11', 'macos-10.15']
        scheme: ['Casimir']
        command: ['test']
        platform: ['macOS', 'iOS', 'tvOS', 'watchOS', 'mac-catalyst']
        exclude:
          # excluding xcodes not present on given macOS versions
          - macos: 'macos-11'
            xcode: '12.0.1'
          - macos: 'macos-10.15'
            xcode: '13.0'
          - macos: 'macos-10.15'
            xcode: '12.5.1'
          - macos: 'macos-10.15'
            xcode: '13.2.1'
          # excluding watchOS builds for xcode <12.5 (API restriction)
          - platform: 'watchOS'
            xcode: '12.0.1'
          - platform: 'watchOS'
            xcode: '12.4'
          # excluding macOS / mac-catalyst builds because of custom platform restrictions
          - platform: 'macOS'
            macos: 'macos-10.15'
          - platform: 'mac-catalyst'
            macos: 'macos-10.15'
          - platform: 'mac-catalyst'
            xcode: '13.0'
    steps:
    - name: Switch xcode to ${{ matrix.xcode }}
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Double-check macOS version (${{ matrix.macos }})
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations for ${{ matrix.scheme }}
      run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: ${{ matrix.platform }}
        scheme: ${{ matrix.scheme }}
        action: ${{ matrix.command }} 
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
