name: Build and test all  platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build_and_test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} 
    strategy:
      fail-fast: false
      matrix:
        xcode: ['14.1', '14.0.1', '13.2.1', '12.5.1']
        macos: ['macos-12', 'macos-11']
        scheme: ['Casimir']
        command: ['test']
        platform: ['macOS', 'iOS', 'tvOS', 'watchOS']
        exclude:
          # excluding xcodes not present on given macOS versions
          - macos: 'macos-11'
            xcode: '14.1'
          - macos: 'macos-11'
            xcode: '14.0.1'
          - macos: 'macos-12'
            xcode: '12.5.1'
          # excluding matrix entries with invalid OS version
          - macos: 'macos-11'
            xcode: '13.2.1'
            platform: 'macOS'
          - macos: 'macos-11'
            xcode: '12.4'
            platform: 'macOS'
    steps:
    - name: Switch xcode to ${{ matrix.xcode }}
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Double-check macOS version (${{ matrix.macos }})
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations for ${{ matrix.scheme }}
      run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: ${{ matrix.platform }}
        scheme: ${{ matrix.scheme }}
        action: ${{ matrix.command }} 
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
