name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
