name: Build for all  platforms
# https://stackoverflow.com/questions/60245159/how-can-i-build-a-swift-package-for-ios-over-command-line#62246008
# https://medium.com/xcblog/speed-up-ios-ci-using-test-without-building-xctestrun-and-fastlane-a982b0060676

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *
  
jobs:
  quickdiag:
    continue-on-error: true
    runs-on: macos-latest
    steps:
    - name: OS version
      run: sw_vers
    - name: Code checkout
      uses: actions/checkout@v2
    - name: List virtual machine contents
      run: ls -al
    - name: List development apps
      run: ls -al /Applications
    - name: Select xcode 12.0.1
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: (12.0.1) Check xcodebuild version
      run: xcodebuild -version
    - name: (12.0.1) Show buildable schemes
      run: xcodebuild -list 
    - name: (12.0.1) Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Casimir
    - name: Select xcode 12.0.1
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: (12.4) Check xcodebuild version
      run: xcodebuild -version
    - name: (12.4) Show buildable schemes
      run: xcodebuild -list 
    - name: (12.4) Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Casimir
  multiplatform_build:
    continue-on-error: true
    runs-on: macos-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: xcodebuild version
      run: xcodebuild -version
    - name: Build  macOS (10.15)
      run: xcodebuild -scheme Casimir -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  macOS Catalyst (10.15)
      run: xcodebuild -scheme Casimir -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  iOS (14.4)
      run: xcodebuild -scheme Casimir -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
    - name: Build  tvOS (14.3)
      run: xcodebuild -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.3,name=Apple TV 4K'
#    - name: Build  watchOS (7.2)
#      run: xcodebuild -scheme Casimir -destination 'platform=watchOS Simulator,OS=7.2,name=Apple Watch Series 6 - 44mm' –skip-testing
    - name: Switch to Xcode 12.0.1
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Build  iOS (14.0)
      run: xcodebuild -scheme Casimir -destination 'platform=iOS Simulator,OS=14.0,name=iPad Pro (12.9-inch) (4th generation)'
    - name: Build  tvOS (14.0)
      run: xcodebuild -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.0,name=Apple TV'
#    - name: Build  watchOS (7.0)
#      run: xcodebuild -scheme Casimir -destination 'platform=watchOS Simulator,OS=7.0,name=Apple Watch Series 4 - 40mm'      
  tests:
    runs-on: macos-latest
    steps:
    - name: Build  macOS (10.15)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  macOS Catalyst (10.15)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  iOS (14.4)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
    - name: Build  tvOS (14.3)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.3,name=Apple TV 4K'
    - name: Switch to Xcode 12.0.1
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Build  iOS (14.0)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=iOS Simulator,OS=14.0,name=iPad Pro (12.9-inch) (4th generation)'
    - name: Build  tvOS (14.0)
      run: xcodebuild test-without-building -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.0,name=Apple TV'
