name: Build and test for all  platforms
# https://stackoverflow.com/questions/60245159/how-can-i-build-a-swift-package-for-ios-over-command-line#62246008
# https://medium.com/xcblog/speed-up-ios-ci-using-test-without-building-xctestrun-and-fastlane-a982b0060676
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
# https://github.com/actions/virtual-environments
# https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  ci_machine_quickdiag_xcode_12_0_1:
    runs-on: macos-latest
    steps:
    - name: OS version
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2.3.4
    - name: Switch to xcode 12.0.1
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '12.0'
    - name: List virtual machine contents
      run: ls -al
    - name: List development apps
      run: ls -al /Applications
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Casimir
  ci_machine_quickdiag_xcode_latest:
    runs-on: macos-latest
    steps:
    - name: OS version
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2.3.4
    - name: Switch to latest xcode
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - name: List virtual machine contents
      run: ls -al
    - name: List development apps
      run: ls -al /Applications
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Casimir
  multiplatform_build_xcode_12_0_1:
    runs-on: macos-latest
    needs: ci_machine_quickdiag_xcode_12_0_1
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Switch to xcode 12.0.1
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '12.0'
    - name: xcodebuild version
      run: xcodebuild -version
    - name: Build  iOS (14.0)
      run: xcodebuild -scheme Casimir -destination 'platform=iOS Simulator,OS=14.0,name=iPad Pro (12.9-inch) (4th generation)'
    - name: Build  tvOS (14.0)
      run: xcodebuild -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.0,name=Apple TV'
#    - name: Build  watchOS (7.0)
#      run: xcodebuild -scheme Casimir -destination 'platform=watchOS Simulator,OS=7.0,name=Apple Watch Series 4 - 40mm'
  multiplatform_build_xcode_latest:
    runs-on: macos-latest
    needs: ci_machine_quickdiag_xcode_latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Switch to latest xcode
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - name: xcodebuild version
      run: xcodebuild -version
    - name: Build  macOS (10.15)
      run: xcodebuild -scheme Casimir -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  macOS Catalyst (10.15)
      run: xcodebuild -scheme Casimir -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build  iOS (14.4)
      run: xcodebuild -scheme Casimir -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
    - name: Build  tvOS (14.3)
      run: xcodebuild -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.3,name=Apple TV 4K'
#    - name: Build  watchOS (7.2)
#      run: xcodebuild -scheme Casimir -destination 'platform=watchOS Simulator,OS=7.2,name=Apple Watch Series 6 - 44mm' –skip-testing
  multiplatform_test_xcode_12_0_1:
    runs-on: macos-latest
    needs: [ci_machine_quickdiag_xcode_12_0_1, multiplatform_build_xcode_12_0_1]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Switch to xcode 12.0.1
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '12.0'
    - name: xcodebuild version
      run: xcodebuild -version
    - name: Test  iOS (14.0)
      run: xcodebuild test -scheme Casimir -destination 'platform=iOS Simulator,OS=14.0,name=iPad Pro (12.9-inch) (4th generation)'
    - name: Test  tvOS (14.0)
      run: xcodebuild test -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.0,name=Apple TV'
  multiplatform_test_xcode_latest:
    runs-on: macos-latest
    needs: [ci_machine_quickdiag_xcode_latest, multiplatform_build_xcode_latest]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Switch to latest xcode
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - name: xcodebuild version
      run: xcodebuild -version
   - name: Test  macOS (10.15)
     run: xcodebuild test -scheme Casimir -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
   - name: Test  macOS Catalyst (10.15)
     run: xcodebuild test -scheme Casimir -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Test  iOS (14.4)
      run: xcodebuild test -scheme Casimir -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
    - name: Test  tvOS (14.3)
      run: xcodebuild test -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.3,name=Apple TV 4K'
