name: Build for all  platforms
# https://stackoverflow.com/questions/60245159/how-can-i-build-a-swift-package-for-ios-over-command-line#62246008

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 10 * * 2
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: xcodebuild -scheme Casimir -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - run: xcodebuild -scheme Casimir -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
    - run: xcodebuild -scheme Casimir -destination 'platform=tvOS Simulator,OS=14.3,name=Apple TV 4K'
    - run: xcodebuild -scheme Casimir -destination 'platform=watchOS Simulator,OS=7.2,name=Apple Watch Series 6 - 44mm'
